### ISSUE TITLE
Monorepo Setup

### ISSUE THREAD

**Issue by likern** [breeffy/react-native-calendar#68]
**TODO:**

- [x] #69
- [x] #71
- [x] #70
- [x] #72
- [x] #73

**CI:**
- [x] #82 

**Documentation Cleanup:**

- [x] Update changelog
- [x] Remove **Usage** section - all examples should be shown in storybook playground. Closes #40
- [x] Remove **Calendar properties** description - this is already explained in TypeScript types and TSDoc 
- [x] Update **Copyright** to 2022 year
- [x] Mention where to find example / usage code
- [x] Explain dependencies / peerDependencies policy
- [x] Add version matrix for every component
- [x] Explain iOS / MacOS / Windows / Web support

**Update Scripts:**

- [x] #78
